name: Scrape

on:
  schedule:
    - cron: "0 0 * * 1" # Executes every Monday at midnight

jobs:
  execute_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Jupyter
        run: |
          pip install jupyter

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --execute scrape.ipynb

      - name: Commit and push if it changed
        if: always()
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
